// <auto-generated />
namespace XYZ.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removestatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removestatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201901170134587_removestatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
